### ISSUE TITLE
PANIC: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by rtrentin73** [CiscoDevNet/terraform-provider-mso#31]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1
+ provider registry.terraform.io/ciscodevnet/mso v0.2.0

### MSO version

Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1
+ provider registry.terraform.io/ciscodevnet/mso v0.2.0

### APIC version and APIC Platform for Site Level Resources

capic 5.2(1g) on aws

### Affected Resource(s)

* data.mso_site

### Terraform Configuration Files

terraform {
  required_providers {
    aci = {
      source  = "CiscoDevNet/aci"
      version = "0.7.1"
    }
    mso = {
      source  = "CiscoDevNet/mso"
      version = "0.2.0"
    }
  }
}

provider "aci" {
  username = var.capic_user
  password = var.capic_password
  url      = var.capic_url
  insecure = true
}

provider "mso" {
  username = var.msc_user
  password = var.msc_password
  url      = var.msc_url
  insecure = true
  platform = "nd"
}

data "mso_site" "aws_site" {
  name = "aws-va"
}

### Debug Output

2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: HTTP Request: POST https://173.36.211.22/api/v1/auth/login
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 nHTTP Response: 200 200 OK &{200 OK 200 HTTP/1.1 1 1 map[Content-Length:[1760] Content-Type:[application/json] Date:[Mon, 05 Jul 2021 20:09:56 GMT] Set-Cookie:[AuthCookie=eyJhbGciOiJSUzI1NiIsImtpZCI6ImtlZDg2d295cDEyamQ1eDM0cWc0ZWwzbnpqYzRnbnMxIiwidHlwIjoiSldUIn0.eyJleHAiOjE2MjU1MTY5OTUsImlhdCI6MTYyNTUxNTc5NSwiaWQiOiI0OGQxMDViZGZiYzQ5YTVmY2YzOWExMGI5NjEzODZlNjFkZmU0MDA4NWNiMDMxNWQ4MThiNzYxYzU3MzVkYWZhIiwiaXNzIjoibmQiLCJyYmFjIjpbeyJkb21haW4iOiJhbGwiLCJyb2xlc1IiOjE2Nzc3MjE2LCJyb2xlc1ciOjF9XSwic2Vzc2lvbmlkIjoidkNvYUM0NzRIQTd4TThPaGJNU1Vjc2VJIiwidXNlcmZsYWdzIjowLCJ1c2VyaWQiOjI1MDAyLCJ1c2VybmFtZSI6ImFkbWluIiwidXNlcnR5cGUiOiJsb2NhbCJ9.JKfvhxhqZUNHisb0CjsYqb3BRUYWDtDy6cN7MJWPAZ2LNI-sN5Gyn6I58PopAJvGZBk7rokIauejyg0dDMsMSXGEdXvg9CbYyZjoYxUoqY-t3CLEHZHokOAu1cmxSR4PAOvWfk-vWOTmBYoFE8_bdc1pm0IAq7xFyz5diK1rET8e_MtzcKUgeCxD_IEvKS1hHOa7YqVJ9P7HzqpbwMI1ugIvFxjmAN2juXwv8oddOXJuYwYp63kcVAhcRCRwnN7BYHRkIRfcio1ZYNZ3FFHgF74vHIJLt1PuxyjyowJLuJVBHNWUusPKip5AOYYYHy25mLx8sKBpifLTLvHpCrGuZg; Max-Age=1200] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff] X-Xss-Protection:[1; mode=block]] 0xc000079840 1760 [] false false map[] 0xc0000b8800 0xc0000f2000}
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0:  HTTP response unique string POST https://173.36.211.22/api/v1/auth/login {"jwttoken":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImtlZDg2d295cDEyamQ1eDM0cWc0ZWwzbnpqYzRnbnMxIiwidHlwIjoiSldUIn0.eyJleHAiOjE2MjU1MTY5OTUsImlhdCI6MTYyNTUxNTc5NSwiaWQiOiI0OGQxMDViZGZiYzQ5YTVmY2YzOWExMGI5NjEzODZlNjFkZmU0MDA4NWNiMDMxNWQ4MThiNzYxYzU3MzVkYWZhIiwiaXNzIjoibmQiLCJyYmFjIjpbeyJkb21haW4iOiJhbGwiLCJyb2xlc1IiOjE2Nzc3MjE2LCJyb2xlc1ciOjF9XSwic2Vzc2lvbmlkIjoidkNvYUM0NzRIQTd4TThPaGJNU1Vjc2VJIiwidXNlcmZsYWdzIjowLCJ1c2VyaWQiOjI1MDAyLCJ1c2VybmFtZSI6ImFkbWluIiwidXNlcnR5cGUiOiJsb2NhbCJ9.JKfvhxhqZUNHisb0CjsYqb3BRUYWDtDy6cN7MJWPAZ2LNI-sN5Gyn6I58PopAJvGZBk7rokIauejyg0dDMsMSXGEdXvg9CbYyZjoYxUoqY-t3CLEHZHokOAu1cmxSR4PAOvWfk-vWOTmBYoFE8_bdc1pm0IAq7xFyz5diK1rET8e_MtzcKUgeCxD_IEvKS1hHOa7YqVJ9P7HzqpbwMI1ugIvFxjmAN2juXwv8oddOXJuYwYp63kcVAhcRCRwnN7BYHRkIRfcio1ZYNZ3FFHgF74vHIJLt1PuxyjyowJLuJVBHNWUusPKip5AOYYYHy25mLx8sKBpifLTLvHpCrGuZg","username":"admin","usertype":"local","rbac":"[{\"domain\":\"all\",\"rolesR\":16777216,\"rolesW\":1}]","statusCode":200,"token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImtlZDg2d295cDEyamQ1eDM0cWc0ZWwzbnpqYzRnbnMxIiwidHlwIjoiSldUIn0.eyJleHAiOjE2MjU1MTY5OTUsImlhdCI6MTYyNTUxNTc5NSwiaWQiOiI0OGQxMDViZGZiYzQ5YTVmY2YzOWExMGI5NjEzODZlNjFkZmU0MDA4NWNiMDMxNWQ4MThiNzYxYzU3MzVkYWZhIiwiaXNzIjoibmQiLCJyYmFjIjpbeyJkb21haW4iOiJhbGwiLCJyb2xlc1IiOjE2Nzc3MjE2LCJyb2xlc1ciOjF9XSwic2Vzc2lvbmlkIjoidkNvYUM0NzRIQTd4TThPaGJNU1Vjc2VJIiwidXNlcmZsYWdzIjowLCJ1c2VyaWQiOjI1MDAyLCJ1c2VybmFtZSI6ImFkbWluIiwidXNlcnR5cGUiOiJsb2NhbCJ9.JKfvhxhqZUNHisb0CjsYqb3BRUYWDtDy6cN7MJWPAZ2LNI-sN5Gyn6I58PopAJvGZBk7rokIauejyg0dDMsMSXGEdXvg9CbYyZjoYxUoqY-t3CLEHZHokOAu1cmxSR4PAOvWfk-vWOTmBYoFE8_bdc1pm0IAq7xFyz5diK1rET8e_MtzcKUgeCxD_IEvKS1hHOa7YqVJ9P7HzqpbwMI1ugIvFxjmAN2juXwv8oddOXJuYwYp63kcVAhcRCRwnN7BYHRkIRfcio1ZYNZ3FFHgF74vHIJLt1PuxyjyowJLuJVBHNWUusPKip5AOYYYHy25mLx8sKBpifLTLvHpCrGuZg"}
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 [DEBUG] Exit from do method
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 HTTP request after injection GET api/v1/sites
2021-07-05T16:09:56.057-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 [DEBUG] Begining DO method https://173.36.211.22/api/v1/sites
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: HTTP Request: GET https://173.36.211.22/api/v1/sites
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 nHTTP Response: 200 200 OK &{200 OK 200 HTTP/1.1 1 1 map[Cache-Control:[no-cache] Content-Length:[874] Content-Type:[application/json] Date:[Mon, 05 Jul 2021 20:09:56 GMT] Expires:[Thu, 01 Jan 1970 00:00:01 GMT] Server:[nginx] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Ratelimit-Limit:[-1] X-Ratelimit-Remaining:[-1] X-Ratelimit-Reset:[1559582945] X-Xss-Protection:[1; mode=block]] 0xc00020c380 874 [] false false map[] 0xc0000b8700 0xc0000f2000}
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0:  HTTP response unique string GET https://173.36.211.22/api/v1/sites {"sites":[{"id":"604cb28e3600008313fdc897","name":"site1","urls":["https://172.21.208.173","https://172.21.208.174","https://172.21.208.175"],"username":"Cisco_MSO_UmVTPDNd","password":"******","apicSiteId":"1","labels":[],"platform":"on-premise","apicVersion":"5.1(3e)","maintenanceMode":false,"health":{}},{"id":"6052a9213500002d68f627fa","name":"site2","urls":["https://172.21.208.241","https://172.21.208.242","https://172.21.208.243"],"username":"Cisco_MSO_UmVTPDNd","password":"******","apicSiteId":"2","labels":[],"platform":"on-premise","apicVersion":"5.1(3e)","maintenanceMode":false,"health":{}},{"id":"60df74939717b2b2e14a2f04","name":"aws-va","urls":["https://3.82.89.75"],"username":"Cisco_MSO_UmVTPDNd","password":"******","apicSiteId":"3","labels":null,"platform":"cloud","cloudProviders":["aws"],"apicVersion":"5.2(1g)","maintenanceMode":false,"health":{}}]}
2021-07-05T16:09:56.207-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 2021/07/05 16:09:56 [DEBUG] Exit from do method
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: PANIC: interface conversion: interface {} is nil, not []interface {}
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: goroutine 40 [running]:
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: github.com/terraform-providers/terraform-provider-mso/mso.datasourceMSOSiteRead(0xc00017acb0, 0x1cd01a0, 0xc00017a1c0, 0xc00017acb0, 0x0)
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	github.com/terraform-providers/terraform-provider-mso/mso/datasource_mso_site.go:141 +0x131a
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc00053d560, 0xc0000ad9c0, 0x1cd01a0, 0xc00017a1c0, 0xc0001a7ca0, 0x1, 0x0)
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:403 +0x88
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000170900, 0xc0001c5ad0, 0xc0000ad9c0, 0xc0000ad9c0, 0x0, 0x0)
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:451 +0x8f
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000100d48, 0x1fa8fe0, 0xc000194c00, 0xc000079300, 0xc000100d48, 0xc000194c00, 0xc000234b78)
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:1036 +0x45d
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1cee1c0, 0xc000100d48, 0x1fa8fe0, 0xc000194c00, 0xc00027f080, 0x0, 0x1fa8fe0, 0xc000194c00, 0xc00031e0e0, 0x6a)
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x217
2021-07-05T16:09:56.210-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001380, 0x1fb42c0, 0xc000082900, 0xc0000b8600, 0xc000191470, 0x271e670, 0x0, 0x0, 0x0)
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: google.golang.org/grpc.(*Server).handleStream(0xc000001380, 0x1fb42c0, 0xc000082900, 0xc0000b8600, 0x0)
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036250, 0xc000001380, 0x1fb42c0, 0xc000082900, 0xc0000b8600)
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-07-05T16:09:56.211-0400 [DEBUG] provider.terraform-provider-mso_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2021-07-05T16:09:56.213-0400 [ERROR] plugin.(*GRPCProvider).ReadDataSource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:09:56.213-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/ciscodevnet/mso/0.2.0/darwin_amd64/terraform-provider-mso_v0.2.0 pid=70835 error="exit status 2"
2021-07-05T16:09:56.213-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

### Expected Behavior

{
   "sites":[
      {
         "id":"604cb28e3600008313fdc897",
         "name":"site1",
         "urls":[
            "https://172.21.208.173",
            "https://172.21.208.174",
            "https://172.21.208.175"
         ],
         "username":"Cisco_MSO_UmVTPDNd",
         "password":"******",
         "apicSiteId":"1",
         "labels":[
            
         ],
         "platform":"on-premise",
         "apicVersion":"5.1(3e)",
         "maintenanceMode":false,
         "health":{
            
         }
      },
      {
         "id":"6052a9213500002d68f627fa",
         "name":"site2",
         "urls":[
            "https://172.21.208.241",
            "https://172.21.208.242",
            "https://172.21.208.243"
         ],
         "username":"Cisco_MSO_UmVTPDNd",
         "password":"******",
         "apicSiteId":"2",
         "labels":[
            
         ],
         "platform":"on-premise",
         "apicVersion":"5.1(3e)",
         "maintenanceMode":false,
         "health":{
            
         }
      },
      {
         "id":"60df74939717b2b2e14a2f04",
         "name":"aws-va",
         "urls":[
            "https://3.82.89.75"
         ],
         "username":"Cisco_MSO_UmVTPDNd",
         "password":"******",
         "apicSiteId":"3",
         "labels":null,
         "platform":"cloud",
         "cloudProviders":[
            "aws"
         ],
         "apicVersion":"5.2(1g)",
         "maintenanceMode":false,
         "health":{
            
         }
      }
   ]
}

### Actual Behavior

Error: The terraform-provider-mso_v0.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by andreassb** [comment]
This seems to be related to the fact that the Nexus Dashboard version of MSO handles sites inside ND and not i MSO itself. The ND GUI uses "/api/config/v2/addsite/" as API endpoint to create sites, and not "/api/v1/sites"
