### ISSUE TITLE
Terraform destroy causes Terraform Crash!

### ISSUE THREAD

**Issue by anvitha-jain** [CiscoDevNet/terraform-provider-mso#63]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### MSO version

* V 3.3

### APIC version and APIC Platform for Site Level Resources

* V x.x.x and on-prem

### Affected Resource(s)

* resource_mso_schema_template_contract

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
Example file used

### Debug Output

mso_schema.schema1: Destroying... [id=614cdcc62c00002632513cc9]
2021/09/23 13:03:06 [TRACE] UpgradeResourceState: schema version of mso_schema.schema1 is still 1; calling provider "mso" for any other minor fixups
2021/09/23 13:03:06 [TRACE] GRPCProvider: UpgradeResourceState
2021/09/23 13:03:06 [DEBUG] EvalApply: ProviderMeta config value set
2021/09/23 13:03:06 [DEBUG] mso_schema.schema1: applying the planned Delete change
2021/09/23 13:03:06 [TRACE] GRPCProvider: ApplyResourceChange
2021-09-23T13:03:06.620-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 [DEBUG] 614cdcc62c00002632513cc9: Beginning Destroy
2021-09-23T13:03:06.620-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 HTTP request DELETE mso/api/v1/schemas/614cdcc62c00002632513cc9
2021-09-23T13:03:06.620-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 [DEBUG] Begin Injection
2021-09-23T13:03:06.620-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 HTTP request after injection DELETE mso/api/v1/schemas/614cdcc62c00002632513cc9
2021-09-23T13:03:06.620-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 [DEBUG] Begining DO method https://10.23.248.66/mso/api/v1/schemas/614cdcc62c00002632513cc9
2021-09-23T13:03:06.764-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 
2021-09-23T13:03:06.764-0700 [DEBUG] plugin.terraform-provider-mso: HTTP Request: DELETE https://10.23.248.66/mso/api/v1/schemas/614cdcc62c00002632513cc9
2021-09-23T13:03:06.764-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 nHTTP Response: 204 204 No Content &{204 No Content 204 HTTP/1.1 1 1 map[Cache-Control:[no-cache] Content-Language:[en] Date:[Thu, 23 Sep 2021 20:03:06 GMT] Expires:[Thu, 01 Jan 1970 00:00:01 GMT] Server:[nginx] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Ratelimit-Limit:[-1] X-Ratelimit-Remaining:[-1] X-Ratelimit-Reset:[1559582945] X-Xss-Protection:[1; mode=block]] {} 0 [] false false map[] 0xc000326400 0xc0004f2000}
2021-09-23T13:03:06.764-0700 [DEBUG] plugin.terraform-provider-mso: 2021/09/23 13:03:06 
2021-09-23T13:03:06.764-0700 [DEBUG] plugin.terraform-provider-mso:  HTTP response unique string DELETE https://10.23.248.66/mso/api/v1/schemas/614cdcc62c00002632513cc9 
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: 
Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1864c90]
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: 
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: goroutine 39 [running]:
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: github.com/ciscoecosystem/mso-go-client/client.(*Client).DeletebyId(0xc0006581c0, 0xc000294300, 0x27, 0xc00055b9e0, 0x18)
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/github.com/ciscoecosystem/mso-go-client@v1.2.1/client/client_service.go:99 +0xb0
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso: github.com/terraform-providers/terraform-provider-mso/mso.resourceMSOSchemaDelete(0xc0000e8540, 0x1b679c0, 0xc0006581c0, 0x24, 0x2290140)
2021-09-23T13:03:06.766-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/MT/terraform-provider-mso/mso/resource_mso_schema.go:226 +0x177
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00043d050, 0xc0006346e0, 0xc0008562e0, 0x1b679c0, 0xc0006581c0, 0x100fa01, 0xc0003450e0, 0x1b524a0)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:283 +0x4a6
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00023c900, 0xc00014fa18, 0xc0006346e0, 0xc0008562e0, 0x2290140, 0x0, 0x0)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001a8d60, 0x1d41990, 0xc000111d70, 0xc0000e8000, 0xc0001a8d60, 0xc000111d70, 0xc00033fb80)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1b7c3a0, 0xc0001a8d60, 0x1d41990, 0xc000111d70, 0xc000640600, 0x0, 0x1d41990, 0xc000111d70, 0xc0000460a0, 0x9b)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000103500, 0x1d4a038, 0xc000187980, 0xc000326300, 0xc00057e9f0, 0x2251920, 0x0, 0x0, 0x0)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: google.golang.org/grpc.(*Server).handleStream(0xc000103500, 0x1d4a038, 0xc000187980, 0xc000326300, 0x0)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd2c
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001181d0, 0xc000103500, 0x1d4a038, 0xc000187980, 0xc000326300)
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xab
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-09-23T13:03:06.767-0700 [DEBUG] plugin.terraform-provider-mso:     /Users/anvjain/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2021-09-23T13:03:06.769-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-09-23T13:03:06.770-0700 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/ciscodevnet/mso/0.2.1/darwin_amd64/terraform-provider-mso pid=77448 error="exit status 2"
2021/09/23 13:03:06 [DEBUG] mso_schema.schema1: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/09/23 13:03:06 [TRACE] EvalWriteState: writing current state object for mso_schema.schema1
2021/09/23 13:03:06 [TRACE] vertex "mso_schema.schema1 (destroy)": visit complete

### Expected Behavior

destro completes

### Actual Behavior

Terraform Crash
Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

all objects except schema is removed from state file

### References

* #0000

**Comment by shrsr** [comment]
@anvitha-jain I was unable to reproduce the issue. I created a schema and its contract using their respective resources. I was able to use destroy and it succeeded. 
It would help if you provided me with your configuration file. I can test that file and see if there's any issue.

**Comment by shrsr** [comment]
An older configuration file was used when issue was reported.
Works well with the newer one.
