### ISSUE TITLE
mso provider: cloud External EPG  gives "none.get" error from NDO UI

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/terraform-provider-mso#82]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Versions
ND: 2.1.1e
NDO : 3.6(0.88)
Terraform: v1.0.11
mso_plugin: v0.3.2

# Description of problem:
When trying to push External EPG with Terraform, NDO UI gives an error saying "none.yet"   Re-associating the VRF to external EPG from NDO UI works. 

```hcl
data "mso_site" "aws_site10" {
  name = var.aws_aws_site10_name
}


resource "mso_tenant" "tenant" {
  name         = var.tenant_stuff.tenant_name
  display_name = var.tenant_stuff.display_name
  description  = var.tenant_stuff.description
  site_associations {
    site_id           = data.mso_site.aws_site10.id
    vendor            = "aws"
    aws_account_id    = var.awsstuff.aws_account_id
    aws_access_key_id = var.awsstuff.aws_access_key_id
    aws_secret_key    = var.awsstuff.aws_secret_key
  }
  user_associations { user_id = var.user_associations }
  user_associations { user_id = "ff880b89aa55edba5bc5d6490af589da0f8028b3fccbcc65dcb36c6b219e0663" }
  # for remote users, get userID, https://{msoIP}/mso/api/v1/tenants  Terraform Import does not work for ND based NDO
}

### create template and associate with Schema

resource "mso_schema" "schema1" {
  depends_on    = [mso_tenant.tenant]
  name          = var.schema.schema1
  template_name = var.schema.template_name1
  tenant_id     = mso_tenant.tenant.id
}

#### Associate Schema / template with Site

resource "mso_schema_site" "aws_site10" {
  depends_on    = [mso_schema.schema1]
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.aws_site10.id
  template_name = var.schema.template_name1

}

### Create VRF
/**
#Seems like I have to do both "mso_schema_template_vrf" and "mso_schema_site_vrf" for this to work
**/

# First create the VRF
resource "mso_schema_template_vrf" "vrf1" {
  depends_on = [mso_schema_site.aws_site10]
  schema_id  = mso_schema.schema1.id
  #template_name = var.schema.template_name1
  template         = mso_schema.schema1.template_name
  name             = var.schema.vrf_name1
  display_name     = var.schema.vrf_name1
  layer3_multicast = false
  vzany            = false
}

#Why is this needed ?  We should be able to associate the VRF to region from Sitel Loal Template without this block
resource "mso_schema_site_vrf" "aws_site" {
  depends_on = [mso_schema_template_vrf.vrf1]
  schema_id  = mso_schema.schema1.id
  template_name = mso_schema_site.aws_site10.template_name
  site_id       = data.mso_site.aws_site10.id
  vrf_name = var.schema.vrf_name1
}



####  Associate with Region and zones in Site Local Templates
resource "mso_schema_site_vrf_region" "vrfRegion" {
  depends_on         = [mso_schema_site_vrf.aws_site]
  schema_id          = mso_schema.schema1.id
  template_name      = var.schema.template_name1
  site_id            = data.mso_site.aws_site10.id
  vrf_name           = var.schema.vrf_name1
  region_name        = "us-east-1"
  vpn_gateway        = false
  hub_network_enable = true
  hub_network = {
    name        = "TGW"
    tenant_name = "infra"
  }
  cidr {
    cidr_ip = "10.140.0.0/16"
    primary = true
    subnet {
      ip    = "10.140.1.0/24"
      zone  = "us-east-1a"
      usage = "gateway"
    }

    subnet {
      ip    = "10.140.2.0/24"
      zone  = "us-east-1b"
      usage = "gateway"
    }

    subnet {
      ip   = "10.140.3.0/24"
      zone = "us-east-1b"
      #usage = ""
    }

  }
}


resource "mso_schema_template_anp" "anp1" {
  depends_on = [mso_schema_site_vrf_region.vrfRegion]
  schema_id    = mso_schema.schema1.id
  template     = var.schema.template_name1
  name         = var.anp_name1
  display_name = var.anp_name1
}


resource "mso_schema_site_anp" "anp1" {
  depends_on    = [mso_schema_template_anp.anp1]
  schema_id     = mso_schema.schema1.id
  anp_name      = var.anp_name1
  template_name = var.schema.template_name1
  site_id       = data.mso_site.aws_site10.id
}


###Create EPG

resource "mso_schema_template_anp_epg" "anp_epg" {
  depends_on    = [mso_schema_site_anp.anp1]
  schema_id                  = mso_schema.schema1.id
  template_name              = var.schema.template_name1
  anp_name                   = var.anp_name1
  name                       = var.epg_name1
  bd_name                    = var.bd_name1
  vrf_name                   = var.schema.vrf_name1
  display_name               = var.epg_name1
  useg_epg                   = false
  intra_epg                  = "unenforced"
  intersite_multicast_source = false
  preferred_group            = false
}


#
resource "mso_schema_site_anp_epg" "site_anp_epg" {
  depends_on = [mso_schema_template_anp_epg.anp_epg]
  schema_id = mso_schema.schema1.id
  template_name = var.schema.template_name1
  site_id = data.mso_site.aws_site10.id
  anp_name = var.anp_name1
  epg_name = var.epg_name1
}

# epg selector gives UI problem in NDO.  comment this out and configure EPG selector manually from UI for now
resource "mso_schema_site_anp_epg_selector" "epgSel1" {
  depends_on = [mso_schema_site_anp_epg.site_anp_epg]
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.aws_site10.id
  template_name = var.schema.template_name1
  anp_name      = var.anp_name1
  epg_name      = var.epg_name1
  name          = "epgSel1"
  expressions {
    key         = "IP Address"
    operator    = "equals"
    value       = "10.140.0.0/16"
  }
}

## extEPG
## after applying, you need to go in from UI and reassociate the vrf to the ext EPG, othewise you cannot deploy Error:  none.get
resource "mso_schema_template_external_epg" "template_externalepg" {
    depends_on = [mso_schema_template_anp_epg.anp_epg]
    schema_id           = mso_schema.schema1.id
    template_name       = var.schema.template_name1
    external_epg_name   = "extEPG1"
    external_epg_type   = "cloud"
        display_name        = "extEPG1"
        vrf_name            =  var.schema.vrf_name1      # after applying, you need to go in from UI and reassociate the vrf to the ext EPG, othewise you cannot deploy Error:  none.get
        vrf_template_name  = var.schema.template_name1
    anp_name            = var.anp_name1
    site_id             = [data.mso_site.aws_site10.id]
    selector_name       = "extEPGsel1"
    selector_ip         = "0.0.0.0/0"
}
```
# Results of Run (seems fine from Terraform): 
```hcl
mso_schema_template_external_epg.template_externalepg: Creating...
mso_tenant.tenant: Modifying... [id=61ae82941d0000bb9dbc8ac0]
mso_schema_template_external_epg.template_externalepg: Creation complete after 1s [id=extEPG1]
mso_tenant.tenant: Modifications complete after 1s [id=61ae82941d0000bb9dbc8ac0]

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.
```

# Looking from NDO UI, we see error:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/13289754/144933253-cb7dbe05-b103-4fb9-b8d1-78cd1a621ef6.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/13289754/144934103-fc53a66c-8069-4336-aebf-f8bdb4572d67.png">

# Re-associating the external EPG (manually from NDO UI) back again to the VRF works.
![image](https://user-images.githubusercontent.com/13289754/144933905-8478b445-f6f0-4218-a6d5-01ca849e6fd7.png)

# Now, if we try to deploy the config from NDO UI, it works

<img width="653" alt="image" src="https://user-images.githubusercontent.com/13289754/144939359-02617427-a119-4412-a74d-e1172fd9be24.png">

**Comment by richwats** [comment]
I'm seeing the same issue with External EPGs.  Updating the VRF in the NDO GUI fixes this.

**Comment by lhercot** [comment]
This issue should be fixed in v0.3.3. Thanks for reporting it.

**Comment by soumukhe** [comment]
Lionel,

I upgraded to v0.3.3 and it told me that I need to use  “mso_schema_site_external_epg”   to associate the site and that "mso_schema_template_external_epg" does not support site.

So, I modified the template as such:
```hcl
resource "mso_schema_template_external_epg" "template_externalepg" {
    depends_on = [mso_schema_template_anp_epg.anp_epg]
    schema_id           = try(mso_schema.schema1.id)
    template_name       = var.schema.template_name1
    external_epg_name   = "extEPG1"
    external_epg_type   = "cloud"
        display_name        = "extEPG1"
        vrf_name            =  var.schema.vrf_name1
        vrf_template_name  = try(var.schema.template_name1)
    anp_name            = var.anp_name1
    #site_id             = [data.mso_site.aws_site10.id]
    selector_name       = "extEPGsel1"
    selector_ip         = "0.0.0.0/0"
}

resource "mso_schema_site_external_epg" "externalepg" {
   #depends_on = [mso_schema_template_anp_epg.anp_epg]
   depends_on = [mso_schema_template_anp_epg.anp_epg]
   schema_id           = try(mso_schema.schema1.id)
   template_name       = var.schema.template_name1
   external_epg_name   = "extEPG1"
    site_id             = data.mso_site.aws_site10.id

}
```
# Results:
```
panic: runtime error: index out of range [3] with length 0

goroutine 82 [running]:
github.com/terraform-providers/terraform-provider-mso/mso.resourceMSOSchemaSiteExternalEpgRead(0xc00029efc0, 0x10e3480, 0xc00082a000, 0xc000165620, 0x1)
        github.com/terraform-providers/terraform-provider-mso/mso/resource_mso_schema_site_external_epg.go:228 +0xd30
github.com/terraform-providers/terraform-provider-mso/mso.resourceMSOSchemaSiteExternalEpgCreate(0xc00029efc0, 0x10e3480, 0xc00082a000, 0x2, 0x1b69b60)
        github.com/terraform-providers/terraform-provider-mso/mso/resource_mso_schema_site_external_epg.go:176 +0xcea
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00058a240, 0xc0002a0a00, 0xc00000d620, 0x10e3480, 0xc00082a000, 0xfed401, 0xc00056aa98, 0xc00032e810)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000636000, 0xc000165a10, 0xc0002a0a00, 0xc00000d620, 0xc000328e08, 0xc00020c1e8, 0xfeefc0)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000638000, 0x13b8440, 0xc000617f20, 0xc00029eaf0, 0xc000638000, 0xc000617f20, 0xc000321b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10fb040, 0xc000638000, 0x13b8440, 0xc000617f20, 0xc0000455c0, 0x0, 0x13b8440, 0xc000617f20, 0xc0000f8180, 0x167)
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000103680, 0x13c3340, 0xc000214a80, 0xc000176100, 0xc000116d20, 0x1b2f5a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc000103680, 0x13c3340, 0xc000214a80, 0xc000176100, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000364f0, 0xc000103680, 0x13c3340, 0xc000214a80, 0xc000176100)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-mso_v0.3.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by soumukhe** [comment]
Lionel,

I deleted the state and cleaned up from NDO UI and tried again and this is working now.   I had to also comment out the “site_id” key. 
```ccl
resource "mso_schema_template_external_epg" "template_externalepg" {
    depends_on = [mso_schema_template_anp_epg.anp_epg]
    #depends_on = [mso_schema_site_external_epg.externalepg]
    schema_id           = try(mso_schema.schema1.id)
    template_name       = var.schema.template_name1
    external_epg_name   = "extEPG1"
    external_epg_type   = "cloud"
        display_name        = "extEPG1"
        vrf_name            =  var.schema.vrf_name1
        vrf_template_name  = try(var.schema.template_name1)
    anp_name            = var.anp_name1
    #site_id             = [data.mso_site.aws_site10.id]
    selector_name       = "extEPGsel1"
    selector_ip         = "0.0.0.0/0"
}
```

**Comment by soumukhe** [comment]
![image](https://user-images.githubusercontent.com/13289754/146225796-4bcfd0ea-dc59-473c-ad51-99588cbc0718.png)
